[project]
name = "local-doc-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling>=2.92.0",
    "fastapi>=0.136.1",
    "langchain>=1.2.17",
    "langchain-ollama>=1.1.0",
    "pandas>=3.0.2",
    "pydantic>=2.13.3",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.27",
    "qdrant-client>=1.17.1",
    "ruff>=0.15.12",
    "sentence-transformers>=5.4.1",
    "shutils>=0.1.0",
    "uvicorn>=0.46.0",
]
